title: Fuel Serve
author:
  name: 'Fuel Serve ' # NB. the source template has a dumb space in the only place this is used so far, it's included here for faithful reproduction but you probably won't want it
  email: 'fuelserve@example.com'
metadata:
    description: 'In a voice of pure fuel'

globals:
  contacts:
    email: info@example.com
    phone:
      - '(+1) 000 123 456789'
      - '+2 987 654 321'
    address: 'Eiusmod Tempor inc ,St Dolore Place,Kingsport 56777' # optional in template

  social: # these names are added to make the social links show
    twitter: realDonaldExample
    linkedin: porfesionalExample
    facebook: vacuousExample
    dribbble: drabExample
